### ISSUE TITLE
ClassCastException on onAllMarketTickersEvent stream

### ISSUE THREAD

**Issue by tompee26** [binance-exchange/binance-java-api#72] opened 2018-02-16 03:11 UTC
I am getting a class cast exception when using the market ticker event stream.

    Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.binance.api.client.domain.event.AllMarketTickersEvent

Is anyone else having this issue? Code below for reference.

    mWebSocketClient.onAllMarketTickersEvent(new BinanceApiCallback<List<AllMarketTickersEvent>>() {
        @Override
        public void onResponse(List<AllMarketTickersEvent> events) throws BinanceApiException {
            Log.d(TAG, events.get(0).toString());
        }
    });

**Comment by tompee26** [comment] 2018-02-16 05:31
I think the reason here is that Q A v q cannot be parsed as long. Maybe because of a recent update.

**Comment by MetalMiner** [comment] 2018-02-16 11:13
Yes, I am facing the same issue and it is really annoying. Pleace fix this fast!

**Comment by MetalMiner** [comment] 2018-02-19 07:54
The problem is the constructor

 ` public BinanceApiWebSocketListener(BinanceApiCallback<T> callback) {
    this.callback = callback;
    this.eventTypeReference = new TypeReference<T>() {};
  }`

You can't get the Typereference of the callback that way. As a quick fix change the `onMessage` method of the same class as follows:

`@Override
  public void onMessage(WebSocket webSocket, String text) {
  	if (webSocket.request().url().toString().endsWith("ticker@arr"))
  	{
  		eventTypeReference = (TypeReference<T>) new TypeReference<List<AllMarketTickersEvent>>(){};
  	} 	
    ObjectMapper mapper = new ObjectMapper();
    try {
      T event = null;
      if (eventClass == null) {
        event = mapper.readValue(text, eventTypeReference);
      } else {
        event = mapper.readValue(text, eventClass);
      }
      callback.onResponse(event);
    } catch (IOException e) {
      throw new BinanceApiException(e);
    }
  } ` 

This is only a temporary solution of course.

**Comment by joaopsilva** [comment] 2018-02-21 17:22
Hi everyone, I'm unable to reproduce this problem, please make sure you update your repository and you're using the latest version, since there were some recent updates on the websocket-based client.

**Comment by joaopsilva** [comment] 2018-02-21 17:22
For reference, I'm using Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

**Comment by MetalMiner** [comment] 2018-02-23 10:16
I think this is an issue related to the Runtime Environment. I switched to yours an it is working fine. When I am using my default which is 1.8.0_144 it is throwing errors. Could you pleace consider testing the API with newer Runtime versions?

**Comment by PartWizard** [comment] 2018-02-25 16:02
Have the same problem, also the quick fix did not work. Will try with different version now.

**Comment by gokmenkisakol** [comment] 2018-04-06 13:17
Hi, I used this code;

            for (Iterator<AllMarketTickersEvent> iter = response.iterator(); iter.hasNext(); ) 
{

                ObjectMapper mapper = new ObjectMapper();

                AllMarketTickersEvent allMarketTickersEvent = mapper.convertValue(iter.next(), AllMarketTickersEvent.class);
 }

**Comment by mjwchapman** [comment] 2018-04-23 14:52
Pull request https://github.com/binance-exchange/binance-java-api/pull/117 fixes this issue.

**Comment by wrone** [comment] 2018-09-06 19:13
Still not fixed? Struggling with it 👎

**Comment by joaopsilva** [comment] 2018-09-13 00:30
This is now fixed, please update your repo.

**Closed by joaopsilva** 2018-09-13 00:30 UTC
