### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by hellsayenci** [binance-exchange/binance-java-api#25] opened 2018-01-10 13:47 UTC
Hi everyone,

I am trying make an android app that uses this library. I compiled .jar file and successfully added to my android studio project.

My problem is that on some devices, when I try to make an API call, an exception like above had been throwed. Same code working on some emulator, not working on physical devices. 

Any ideas? Thanks.

**Comment by Micha1990** [comment] 2018-01-12 14:42
I have the same issue. Does somebody has a solution for it?

**Comment by klaszlo8207** [comment] 2018-01-15 12:56
+1 for this, on my Galaxy S7 this is working, but on my Nexus6 this end up with a big crash :(

**Comment by Blogshot** [comment] 2018-01-27 11:23
+1 for this

**Comment by gizmochief7** [comment] 2018-02-01 19:39
I had the same problem, and I pulled in the [PR](https://github.com/binance-exchange/binance-java-api/pull/11) which has fixed the issue. There are still many other issues that will affect the stability of a long running process but they seem to be in work too.

**Comment by joaopsilva** [comment] 2018-02-23 10:06
Duplicate of #8.

**Closed by joaopsilva** 2018-02-23 10:06 UTC

**Comment by AdamPavlik** [comment] 2021-04-13 18:42
Library gets time from System.currentTimeMillis(); thats is your machin time, machine time can grift a bit, so you needjust synchronise your time.

for example for windows OS you need just: 
a. Click on clock and select “Change date and time settings”.
b. Click on the “Internet Time” tab.
c. Check if it is set to “synchronize the time with time.windows.com”
d. If the option is selected, click on change settings to check the option “Synchronize with an Internet Time server”
e. Click on OK.

**Comment by jonnyquy** [comment] 2021-11-10 05:47
Your problem will be solved.

 public long TimeZone() {
        try {
            String TIME_SERVER = "time.windows.com";
            NTPUDPClient timeClient = new NTPUDPClient();
            InetAddress inetAddress = InetAddress.getByName(TIME_SERVER);
            TimeInfo timeInfo = timeClient.getTime(inetAddress);
            long returnTime = timeInfo.getMessage().getTransmitTimeStamp().getTime();
            Date time = new Date(returnTime);
            return time.getTime();
        } catch (UnknownHostException ex) {
            Logger.getLogger(ActionTradeSpot.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ActionTradeSpot.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }
