### ISSUE TITLE
is it possible to listen raw trade updates?

### ISSUE THREAD

**Issue by zagorulkinde** [binance-exchange/binance-java-api#70] opened 2018-02-10 17:25 UTC
Hello. Is't possible to get raw trades stream using this library? I know that it's possible to get aggregated trade updates, but i could not find any information about raw trades.

https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

**Comment by fromjgor** [comment] 2018-02-11 18:42
Hello, a similar issue was discussed [here](https://github.com/binance-exchange/binance-java-api/issues/39)

**Comment by joaopsilva** [comment] 2018-02-21 17:26
Duplicate of #39.

**Closed by joaopsilva** 2018-02-21 17:26 UTC
Labels: duplicate
